[book]
title = "Debt Algorand Standard Application (D-ASA)"
authors = ["Cosimo Bassi"]
description = "A standard for debt instruments tokenization on Algorand"
language = "en"
src = "docs"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
smart-punctuation = true
mathjax-support = true
git-repository-url = "https://github.com/cusma/d-asa"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/cusma/d-asa/edit/main/{path}"
site-url = "https://cusma.github.io/d-asa/"

[output.html.fold]
enable = true
level = 3
